### ISSUE TITLE
How to update the Software Architecture Document?

### ISSUE THREAD

**Issue by diderikvw** [global-121/121-platform#1640]
A large part of the documentation of the 121 platform is currently in the so-called Software Architecture Document. This is a Microsoft Word document that is exported/generated from the tool Sparx Enterprise Architect (EA). So the SAD is created/updated in EA. 

As volunteers are starting to contribute to the 121 platform, they are also interested in contributing by updating the SAD. 

How can we make that work?

Short term/easy fix: we give that volunteer one of our EA licenses, so they can use and edit in EA. We may need to migrate from an EA project file to storing the EA data into a database, which allows for more ad-hoc editing by multiple people. If we do not do this, we may run into "conflicts" when multiple people edit the EA project file at the same time. Since the EA project file is binary, it is not possible to resolve these conflicts like with source code.

Long term fix: we move away from EA and migrate documentation to "something else". The question is then: what would this alternative be? Using EA has some great features that we benefit from, so we need to have a good insight into the pros and cons of the new sitation, including the migration path. How are other open source initiatives doing this? Maybe move away from using UML altogether?

**Comment by gulfaraz** [comment]
@diderikvw The [GitHub Wiki](https://github.com/global-121/121-platform/wiki) tab is a viable candidate for this.

**Comment by diderikvw** [comment]
@gulfaraz Thank you for your suggestion. Can you elaborate on this?

I am already using this Wiki to give a brief intro into Enterprise Architect, but found out from experience (in my initial months on 121) that creating a similar way of documenting that I now do in EA takes me about 10 times longer in this Wiki. So an update I can get into EA in 1 hour, would take me well over a day in the Wiki, because of all the manual adding, editing and updating. Furthermore, it will result into more mistakes as I will need to check everything manually as well, while EA lets me edit something in context in 1 place and takes care of the rest.

Or do you suggest to create/structure documentation in a different way entirely? Maybe not using UML or any kind of visual at all, only text-based documentation? And/or significantly reducing the amount of documentation when migrating from EA to the Wiki? Or...?

**Comment by gulfaraz** [comment]
> Can you elaborate on this?

My suggestion is to move all the documentation to the Wiki format. GitHub Wiki allows us to create pages and sub-pages with sufficiently rich content (links, images, videos, all sorts of text formatting - italics, quotes, code, and even bold!). We could treat the wiki as a one-stop-shop to learn everything about the product. This includes manuals, licenses, how-to's, why-did-we's, links to our design files and deployments, everything but the secrets and env vars but also documentation to where these are and how to set them. Think more like we're writing a book on 121 for someone who is trying to understand what we tried to achieve.

Yes, this would make it all bulky and hard to navigate but we would have one place to find all that is needed without having to ask from individuals each time. With the right indexing and page organization skills, it should be possible to make it readable. An added bonus is that the documentation would also be under version control.

> EA takes me about 10 times longer in this Wiki

I believe this will improve with time as you get more comfortable with the process. You could still create the complex content with EA and move it here when required.

> it will result into more mistakes as I will need to check everything manually as well

Shouldn't someone else be doing the reviewing? The [4-eyes principle](https://www.unido.org/overview/member-states/change-management/faq/what-four-eyes-principle#:~:text=The%20four%2Deyes%20principle%20means,of%20authority%20and%20increase%20transparency.) is a good practice to tackle this issue.

> Or do you suggest to create/structure documentation in a different way entirely?

My suggestion is to,
1. move all our existing documentation the GitHub Wiki
2. format all our documentation to make the content readable
3. dedicate time during sprint reviews to review the documentation
4. treat the documentation as the source of truth for all things 121

> Maybe not using UML or any kind of visual at all, only text-based documentation?

[It is possible to add any kind of images to the Wiki.](https://gist.github.com/subfuzion/0d3f19c4f780a7d75ba2)

> And/or significantly reducing the amount of documentation when migrating from EA to the Wiki?

*Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.*

> Or do you have a "good practice" example of a similar open-source initiative that we can learn from?

There is no one project which has the solution, everyone uses it in a way which helps address their unique issues. We can review their approaches and pick what meets our needs.

https://github.com/mozilla-mobile/fenix/wiki
https://github.com/pytorch/pytorch/wiki
https://github.com/Netflix/Hystrix/wiki

**Comment by diderikvw** [comment]
@gulfaraz Great elaboration! :dancers: 
I will respond in detail later. For now, only adding this open source initiative that seems to have comprehensive documentation as well. And is a NodeJS project, plus is somewhat Red Cross-related: healthcare, Africa.

**Comment by diderikvw** [comment]
Hi @gulfaraz,
I am on board with your suggestion of moving all documentation to GitHub and hence out of Enterprise Architect!
The links to various approaches you gave are a good reference, as I believe is the Bhima.
Instead of ("blindly") "move all documentation to the Wiki", I suggest we first do a little bit of research into the existing practices from above links, coming up with a basic structure and topic/content of how we want our documentation to become, also keeping various audiences in mind.
And then "fill that in" with what we already have in EA and in our READMEs. This means also re-assessing our READMEs, to make a conscious decision what goes in the README(s), what in the Wiki and how they are connected/linked.
Anything missing, we add placeholders for later. Anything leftover, we throw away.
I would prefer to do this in a "hackathon" kind of way with the entire team, or least a small group of people willing to pick up this work. I do not want to do all this by myself.
And of course I am looking forward to the perspective of our volunteers. And if they see themselves up to take up or coordinate this work.

**Comment by elwinschmitz** [comment]
@diderikvw  A quick addition to this, as its "on my to-do-list" for quite some time already: https://github.com/HospitalRun

I think that product/project is similar in scope as our HO-portal; and it operates in a very similar context as we (want to).

I haven't looked at their specific type of documentation of "software architecture" yet though...

**Comment by diderikvw** [comment]
Hi @elwinschmitz , very interesting initiative HospitalRun. Looks like a HIMS similar to Bhima, for a similar context, maybe they are "competitors". HospitalRun looks a lot "bigger", in every sense. Just looking at their sheer number of repos and contributors amazes me.

**Comment by elwinschmitz** [comment]
Here a short 'brain dump' following our short conversation this morning @diderikvw ;

The **City of Amsterdam** has a nice 'presence' on GitHub: https://amsterdam.github.io/
It contains interesting 'guides' that we can maybe re-use or refer to. As I think their scope/mindset might be similar to that of 510, in a way.

For a totally different scope/scale: **GitLab**
As they are a "remote only"- and "transparent by default"-company; they might have interesting approaches we can use.
Things like: https://about.gitlab.com/direction/ (their 'roadmap'), but also other more 'applied' things, like documentation...

About diagrams: **Mermaid**, see: https://mermaid-js.github.io/mermaid/#/integrations
I think I was confused with the "native support" in GitLab instead of GitHub.. :(

**Comment by jannisvisser** [comment]
@diderikvw this issue seems like it could be closed right?
