### ISSUE TITLE
Run 121-service with local database - Twilio credentials missing

### ISSUE THREAD

**Issue by steven-guan** [global-121/121-platform#1669]
I'd like to run 121-service connecting to my local database. After modify the config in ormconfig.ts, the connection seems ok. How to figure out the following two issues.

`The "key" argument`

`throw new Error('username is required');`

Following are the logs. 

admin@MACC02W4GHWHTD6 121-service % npm start

> 121-service@ prestart /Users/admin/Documents/GITHUB/121-platform/services/121-service
> ts-node src/scripts seed-prod && npm run migration:run

[Nest] 77188   - 12/18/2020, 10:56:30 AM   [NestFactory] Starting Nest application...
[Nest] 77188   - 12/18/2020, 10:56:31 AM   [InstanceLoader] TypeOrmModule dependencies initialized +443ms
[Nest] 77188   - 12/18/2020, 10:56:33 AM   [InstanceLoader] TypeOrmCoreModule dependencies initialized +2600ms
[Nest] 77188   - 12/18/2020, 10:56:33 AM   [InstanceLoader] ScriptsModule dependencies initialized +0ms
**(node:77188) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be one of type Buffer, TypedArray, DataView, string, or KeyObject. Received type undefined**
    at prepareSecretKey (internal/crypto/keys.js:299:13)
    at new Hmac (internal/crypto/hash.js:98:9)
    at Object.createHmac (crypto.js:139:10)
    at SeedInit.<anonymous> (/Users/admin/Documents/GITHUB/121-platform/services/121-service/src/scripts/seed-init.ts:24:12)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/admin/Documents/GITHUB/121-platform/services/121-service/src/scripts/seed-init.ts:14:58)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:77188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:77188) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> 121-service@ migration:run /Users/admin/Documents/GITHUB/121-platform/services/121-service
> npm run typeorm migration:run

> 121-service@ typeorm /Users/admin/Documents/GITHUB/121-platform/services/121-service
> ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js "migration:run"

query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = '121-service' AND "table_name" = 'custom_migration_table'
query: CREATE TABLE "121-service"."custom_migration_table" ("id" SERIAL NOT NULL, "timestamp" bigint NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_c94070442591b1a8cc964c02bc6" PRIMARY KEY ("id"))
query: SELECT * FROM "121-service"."custom_migration_table" "custom_migration_table"  ORDER BY "id" DESC
No migrations are pending

> 121-service@ start /Users/admin/Documents/GITHUB/121-platform/services/121-service
> node index.js

/Users/admin/Documents/GITHUB/121-platform/services/121-service/node_modules/twilio/lib/rest/Twilio.js:132
    **throw new Error('username is required');**
          ^
Error: username is required
    at new Twilio (/Users/admin/Documents/GITHUB/121-platform/services/121-service/node_modules/twilio/lib/rest/Twilio.js:132:11)
    at initializer (/Users/admin/Documents/GITHUB/121-platform/services/121-service/node_modules/twilio/lib/index.js:9:10)
    at Object.<anonymous> (/Users/admin/Documents/GITHUB/121-platform/services/121-service/src/notifications/twilio.client.ts:1:46)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Module.m._compile (/Users/admin/Documents/GITHUB/121-platform/services/121-service/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/admin/Documents/GITHUB/121-platform/services/121-service/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 121-service@ start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the 121-service@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2020-12-18T02_56_53_982Z-debug.log

**Comment by elwinschmitz** [comment]
This specific error doesn't really have to do with the local database set-up, I think.

The Twilio-API requires a valid 'username' (the ENV-variable `TWILIO_SID`), in the form of `ACabc...` (is has to start with `AC`).

So 2 possible next actions:
- The documentation needs to be updated to explain this
- The code needs to be 'smarter' in the way that the full application isn't dependent on this one ENV-variable to be 'correct';  
  So it should log/prompt with a proper actionable error-message and it should continue to start-up/run all the other features, I think.

If you have suggestions for any of these (or have ideas for other actions), please let us know! ;)

**Comment by steven-guan** [comment]
hmm, signed up a twilio account and specify my twilio info to `TWILIO_SID` and `TWILIO_AUTHTOKEN`. how to solve following errors?
![Screen Shot 2020-12-27 at 6 06 41 PM](https://user-images.githubusercontent.com/6323707/103168453-4ec3f680-486e-11eb-9ad9-ba3a6f13f915.png)

**Comment by steven-guan** [comment]
would be fixed by set these in .env
`APPLICATION_INSIGHT_IKEY=test
APPLICATION_INSIGHT_ENDPOINT=test`

**Comment by elwinschmitz** [comment]
I think we can change the example `.env`-file to prevent these issues in the future.

**Comment by steven-guan** [comment]
> I think we can change the example `.env`-file to prevent these issues in the future.
> Or add some checks in the code before the actual use of the ENV-variables...

yes, it will be better to set some default values to avoid these issues.
