### ISSUE TITLE
Do we have to use ngrok?

### ISSUE THREAD

**Issue by steven-guan** [global-121/121-platform#1670]
Philips blocks ngrok website, any workround?

<img width="879" alt="Screen Shot 2020-12-18 at 11 18 47 AM" src="https://user-images.githubusercontent.com/6323707/102570724-ea44c100-4122-11eb-9bc6-bd14ae019c7b.png">

**Comment by elwinschmitz** [comment]
@steven-guan Ah, too bad.
Any other way to inspect "requests from outside" would also work.

Services like https://smee.io/ could work as well (I haven't tested that with this project yet though).
Or maybe there is some other tool to expose your local instance to the outside world?

Via the ENV-variable you can supply any URL that is accessible by the third-party APIs, to send their callback/responses to.

**Comment by steven-guan** [comment]
downloaded from a public wifi, seems it works well. will verify it whether it can work in Philips's network.
