### ISSUE TITLE
Some problems with building pa-accounts-service

### ISSUE THREAD

**Issue by steven-guan** [global-121/121-platform#1673]
Should i upgrade TS or something?

admin@MACC02W4GHWHTD6 services % docker-compose logs -f PA-accounts-service
Attaching to pa-accounts-service
pa-accounts-service    | 
pa-accounts-service    | > pa-accounts-service@ prestart:dev /home/node/app
pa-accounts-service    | > npm run prestart
pa-accounts-service    | 
pa-accounts-service    | 
pa-accounts-service    | > pa-accounts-service@ prestart /home/node/app
pa-accounts-service    | > npm run migration:run
pa-accounts-service    | 
pa-accounts-service    | 
pa-accounts-service    | > pa-accounts-service@ migration:run /home/node/app
pa-accounts-service    | > npm run typeorm migration:run
pa-accounts-service    | 
pa-accounts-service    | 
pa-accounts-service    | > pa-accounts-service@ typeorm /home/node/app
pa-accounts-service    | > ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js "migration:run"
pa-accounts-service    | 
pa-accounts-service    | Version 9 of Highlight.js has reached EOL and is no longer supported. Please upgrade to version 10.
pa-accounts-service    | query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'pa-accounts' AND "table_name" = 'custom_migration_table'
pa-accounts-service    | query: SELECT * FROM "pa-accounts"."custom_migration_table" "custom_migration_table"  ORDER BY "id" DESC
pa-accounts-service    | No migrations are pending
pa-accounts-service    | 
pa-accounts-service    | > pa-accounts-service@ start:dev /home/node/app
pa-accounts-service    | > tsc-watch --noClear --onSuccess "  node index.js  " --onFailure "echo There was a problem with the build!" -p tsconfig.json
pa-accounts-service    | 
pa-accounts-service    | 
pa-accounts-service    | 
pa-accounts-service    | ----------------------
pa-accounts-service    | 11:20:34 AM - Starting compilation in watch mode...
pa-accounts-service    | node_modules/@nestjs/common/http/http.service.d.ts(13,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | node_modules/@nestjs/core/helpers/http-adapter-host.d.ts(21,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | node_modules/@nestjs/core/helpers/http-adapter-host.d.ts(28,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | node_modules/@nestjs/core/injector/container.d.ts(19,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | node_modules/@nestjs/core/injector/instance-wrapper.d.ts(33,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | node_modules/@nestjs/core/injector/instance-wrapper.d.ts(34,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | node_modules/@nestjs/core/injector/instance-wrapper.d.ts(35,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | node_modules/@nestjs/core/injector/instance-wrapper.d.ts(36,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | node_modules/@nestjs/core/injector/instance-wrapper.d.ts(37,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | node_modules/@nestjs/core/injector/module.d.ts(21,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | node_modules/@nestjs/core/injector/module.d.ts(22,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | node_modules/@nestjs/core/injector/module.d.ts(23,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | node_modules/@nestjs/core/injector/module.d.ts(24,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | node_modules/@nestjs/core/injector/module.d.ts(25,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | node_modules/@nestjs/core/injector/module.d.ts(29,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | node_modules/@nestjs/core/injector/module.d.ts(33,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | node_modules/@nestjs/core/injector/module.d.ts(37,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | node_modules/@nestjs/core/injector/module.d.ts(38,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | node_modules/@nestjs/core/injector/module.d.ts(39,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | node_modules/@nestjs/core/injector/module.d.ts(40,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | node_modules/@nestjs/core/injector/module.d.ts(41,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | node_modules/@nestjs/core/injector/module.d.ts(42,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | node_modules/@nestjs/core/injector/module.d.ts(43,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | node_modules/@nestjs/core/injector/module.d.ts(44,9): error TS1086: An accessor cannot be declared in an ambient context.
pa-accounts-service    | 11:21:53 AM - Found 24 errors. Watching for file changes.
pa-accounts-service    | There was a problem with the build!

**Comment by elwinschmitz** [comment]
I think this can have something to do with the version of `typescript` that is used in the PA-accounts-service (as it is not the same as the 121-service version..)

But I don't think I have the same issue locally, so only a version-mismatch cannot be the only issue... :/

What you could try is to run the service in 'normal' mode and not in 'development/watch'-mode. This will also speed up the service start-up-time.

In `docker-compose.development.yml`: https://github.com/global-121/121-platform/blob/master/services/docker-compose.development.yml#L22

Change the command to: `npm run start`.

Another thing you could do to debug the issues further is to see which version(s) of the dependencies you have installed, via:
`docker-compose exec PA-accounts-service npm ls typescript`

And post the outcome here, so I can compare with my local set-up.

**Comment by steven-guan** [comment]
<img width="636" alt="Screenshot at Jan 03 15-16-25" src="https://user-images.githubusercontent.com/6323707/103473722-b29e7000-4dd6-11eb-8b39-abc8fea21355.png">
upgrade my local typescript version, but it does not work. PA-accounts-service is using 3.5.1

**Comment by steven-guan** [comment]
good new,  after pull #1700, the service is running very well, i can access the swagger ui.
