### ISSUE TITLE
Node Sass used for PA-App does not support Node v15

### ISSUE THREAD

**Issue by steven-guan** [global-121/121-platform#1724]
PA-app is using node-sass 4.13.1. Checked the release note https://github.com/sass/node-sass/releases/tag/v4.13.1, it does not support Node v15.5.1 what i am using. Is it possible to upgrade node-sass to v5.0.0 https://github.com/sass/node-sass/releases/tag/v5.0.0?

**Comment by elwinschmitz** [comment]
Hopefully our dependency (`ionic/core`, I think) will release an update for their package, so we could use _that_...

But this is one of the reasons to use NVM(<https://nvm.sh/>) (or a similar tool) to prevent version-conflicts like this..

When using Node v10 it'll work, I'm not 100% sure about Node v14 (the current LTS-version), but that'll be the next 'target' to upgrade the interfaces to.

**Comment by steven-guan** [comment]
Tried Node v14.15.4 and v13.14.0, neither works. Downgrade to v12.20.1, finally it works. Suggest that we upgrade node-sass to a newer version to support v14.

**Comment by steven-guan** [comment]
![Screen Shot 2020-12-27 at 6 06 41 PM](https://user-images.githubusercontent.com/6323707/104287532-8dee7a80-54f1-11eb-8a33-280b01b457f1.png)
i am using macOS 10.15.7. seems node v10 does not work.

**Comment by elwinschmitz** [comment]
It seems that something from Node v12 is still on your system and/or being used?

I have it working on my machine with macOS 10.15.7 with a Node version (via NVM) of v10.22...

You should try to at least remove your current `node_modules/`-folder(s) I think...

**Comment by elwinschmitz** [comment]
See: AB#1543
See: AB#3097

Some refactoring and future-proofing is on our roadmap in the near future, so closing this here for now.
