### ISSUE TITLE
Remove Sovrin from 121 platform

### ISSUE THREAD

**Issue by diderikvw** [global-121/121-platform#1975]
As Administrator of a 121 platform instance
I do not want to bother with Sovrin since that we concluded it does not have added value
So that I do not need to spend time making Sovrin work of fixing it.

- [x] Prepare
- [x] Do it
- [x] Review

**Comment by diderikvw** [comment]
Refinement:

    Elwin and Jannis will discuss who does what when picking up the work in this item.
    See notes below.
    Replace DID for a non-Sovrin ID (ConnectionID).
    Test the whole flow, including all paths.
    Analyse if data migration for deployment to production is necessary. If so, see if new PBI needs to be created and refined.
    Update deployment script to not include Docker services.

**Comment by diderikvw** [comment]
- [ ] eewrerw
- [ ] ewrewewr

**Comment by elwinschmitz** [comment]
Done ✅ in release v1.3.0, see: [CHANGELOG.md / v1.3.0](https://github.com/global-121/121-platform/blob/master/CHANGELOG.md#130---2021-05-05)
