### ISSUE TITLE
Create test/demo data-set with all possible variations of program/PA-data

### ISSUE THREAD

**Issue by diderikvw** [global-121/121-platform#1976]
Refinement:

    Goal of first slice: to test with around 2000 PAs in the platform.
    Create endpoint to upload CSV-file with PA-data to create PAs
        For Admin only...
        status = "registered" (so dates are set accordingly)
        PA-data only columns
    Write test-workflow for manual tests (before a release)
    What do we want to test with (2k) PAs?
        in wiki?
        see /features/-files?
        1: Do a payment
        2: Send/trigger reminder-notification
        3: Receive incoming "yes"-message
        4:
        5: 
    Update/set Definition of Done
        Do manual test(s)

    Research limits of Twilio API
    Create more follow-up PBIs

**Comment by elwinschmitz** [comment]
See: [CHANGELOG / v1.3.0 / Added](https://github.com/global-121/121-platform/blob/master/CHANGELOG.md#added-1)
