### ISSUE TITLE
Upgrade Tar dependency to avoid a severe vulnerability

### ISSUE THREAD

**Issue by basxib** [global-121/121-platform#28]
A vulnerability was found in node-tar before version 4.4.2. An Arbitrary File Overwrite issue exists when extracting a tarball containing a hardlink to a file that already exists on the system, in conjunction with a later plain file with the same name as the hardlink. This plain file content replaces the existing file content.

**Comment by elwinschmitz** [comment]
This is an issue of a dependency-of-a-dependency. :(

See also: https://github.com/angular/angular-devkit-build-angular-builds/issues/5

Someone managed to fix it for his situation: https://github.com/angular/angular-cli/issues/14221#issuecomment-493111591

Let's see if I can do something similar...

**Comment by elwinschmitz** [comment]
Hmm.. no cigar. :(

https://github.com/angular/angular-cli/issues/14138#issuecomment-493679728

I think we just need to wait and keep an eye on: https://github.com/angular/angular-cli/releases

As that is our dependency.

**Comment by elwinschmitz** [comment]
Yes! Our wishes are heard!: https://github.com/angular/angular-cli/releases/tag/v8.0.0

That will solve this issue.. (and hopefully not introduce any new ones...)
